In [12]:
import numpy as np

# Definir la matriz A
D = np.array([[1, 0], [0, -1]])

print("Matriz D:",D)
P = np.array([[1, 1], [-1, 1]])
A = np.dot(np.dot(np.linalg.inv(P), D), P)


print("Matriz A:",A)


Matriz D: [[ 1  0]
 [ 0 -1]]
Matriz A: [[0. 1.]
 [1. 0.]]


In [38]:
import numpy as np


# Crear el diccionario de conversión
abc_dict = {chr(i + 64): i for i in range(1, 27)}  # A = 1, B = 2, ..., Z = 26
abc_dict[" "] = 0  # Espacio = 0

# Mostrar el diccionario
print(abc_dict)
def text_to_numbers(text):
    text = text.upper()  # Convertimos a mayúsculas para evitar errores
    return [abc_dict[char] for char in text if char in abc_dict]

# Prueba con "LA VIDA ES BELLA"
frase = "Y AHORA QUIEN PODRA AYUDARNOS "
numeros = text_to_numbers(frase)
print(numeros)

# Convertir la lista de números en una matriz de filas
numeros_matriz = np.array(numeros).reshape(-1, 2)
print(numeros_matriz.T)





{'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'I': 9, 'J': 10, 'K': 11, 'L': 12, 'M': 13, 'N': 14, 'O': 15, 'P': 16, 'Q': 17, 'R': 18, 'S': 19, 'T': 20, 'U': 21, 'V': 22, 'W': 23, 'X': 24, 'Y': 25, 'Z': 26, ' ': 0}
[25, 0, 1, 8, 15, 18, 1, 0, 17, 21, 9, 5, 14, 0, 16, 15, 4, 18, 1, 0, 1, 25, 21, 4, 1, 18, 14, 15, 19, 0]
[[25  1 15  1 17  9 14 16  4  1  1 21  1 14 19]
 [ 0  8 18  0 21  5  0 15 18  0 25  4 18 15  0]]


In [39]:
# hacer la transformación

numeros_cifrados = np.dot(A, numeros_matriz.T)
print(numeros_cifrados)

# Convertir la matriz de números cifrados en una lista
numeros_cifrados = numeros_cifrados.T.flatten()
print(numeros_cifrados)

[[ 0.  8. 18.  0. 21.  5.  0. 15. 18.  0. 25.  4. 18. 15.  0.]
 [25.  1. 15.  1. 17.  9. 14. 16.  4.  1.  1. 21.  1. 14. 19.]]
[ 0. 25.  8.  1. 18. 15.  0.  1. 21. 17.  5.  9.  0. 14. 15. 16. 18.  4.
  0.  1. 25.  1.  4. 21. 18.  1. 15. 14.  0. 19.]


In [40]:
## devolver a texto

A_inv = np.linalg.inv(A)

numeros_descifrados = np.dot(A_inv, numeros_cifrados.reshape(-1, 2).T)
numeros_descifrados = numeros_descifrados.T.flatten()
print(numeros_descifrados)

[25.  0.  1.  8. 15. 18.  1.  0. 17. 21.  9.  5. 14.  0. 16. 15.  4. 18.
  1.  0.  1. 25. 21.  4.  1. 18. 14. 15. 19.  0.]


In [41]:
def numbers_to_text(numbers):
    reverse_dict = {v: k for k, v in abc_dict.items()}  # Invertimos el diccionario
    return "".join(reverse_dict[num] for num in numbers)

# Prueba con los números obtenidos antes
texto_recuperado = numbers_to_text(numeros_descifrados)
print(texto_recuperado)



Y AHORA QUIEN PODRA AYUDARNOS 
